# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.16.3

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          name: Install and Test
          script:
            - npm ci
            - npm run test:with-coverage
  branches:
    master:
      - step:
          caches:
            - node
          name: Release version
          script:
            - whoami
            - npm config set unsafe-perm true
            - npm ci
            - npm run test:with-coverage
            - npm version minor -m "%s version release"